version: '3.8'

services:
  # PHP Apache
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: yii2_blog_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/apache.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    environment:
      - YII_ENV=dev

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: yii2_blog_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: yii2basic
      MYSQL_USER: yii2user
      MYSQL_PASSWORD: yiipassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: yii2_blog_pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db

volumes:
  db_data: